version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todolist-backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend/data:/app/data"

  frontend:
    build: ./todolist-frontend
    container_name: todolist-frontend
    ports:
      - "80:80"
